docker container prune -y
docker image remove eightfish-m2-simple_app-a 
docker image remove eightfish-m2-simple_app-b
docker image remove eightfish-m2-simple_app-c 
docker image remove eightfish-m2-simple_app-d 
docker image remove eightfish-m2-http_gate
docker image remove eightfish-m2-subxtproxy
docker image remove eightfish-m2-subnode 
docker image remove eightfish-m2-build
